# Tools
PREFIX  := arm-none-eabi-
CC      := $(PREFIX)gcc
OBJCOPY := $(PREFIX)objcopy
AR      := $(PREFIX)ar

# Flags
CFLAGS   := -mcpu=cortex-m3 -mthumb -ffreestanding -I../include
LDSCRIPT := ../tools/stm32f103.ld
LDFLAGS  := -nostdlib -T $(LDSCRIPT)
LIBS     := ../library/library.a

# Compile rules
%.o: %.c
	$(CC) $(CFLAGS) -c $^ -o $@
%.o: %.S
	$(CC) $(CFLAGS) -c $^ -o $@

# Turn an elf into a flat binary
%.bin: %.elf
	$(OBJCOPY) $^ -o $@ -O binary
